config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    get 'omniauth' => 'users/registrations#omniauth'
    post 'users/guest_user', to: 'users/sessions#guest_user'
  end
  resources :articles do
    get :search,on: :collection
  end

  resources :main_pages
  resources :top_pages

  resources :profiles do
    get :search, on: :collection
   member do
    get "friend"
    get "article"
    get "group"
    get "comment"
    get "friend_request"
   end
  end

  resources :friends,only:[:create,:destroy,:update]
   
  resources :comments
  resources :groups do
    get :search, on: :collection
    member do
       post "register"
    end
  end

  get 'profile', to: 'profiles#mypage'

  authenticated :user do
    root :to => 'profiles#mypage'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "top_pages#index"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :articles
  has_many :members
  has_many :groups, through: :members
  mount_uploader :avatar, AvatarUploader
  has_many :follow_friends,  class_name:  "Friend",
                                   foreign_key: "from_user_id",
                                   dependent:   :destroy
  has_many :follower_friends, class_name:  "Friend",
                                   foreign_key: "to_user_id",
                                   dependent:   :destroy
  has_many :from_users, through: :follower_friends,  source: :from_user
  has_many :to_users, through: :follow_friends, source: :to_user
  validates :nickname,presence: true
  validates :text,presence: true

  #フォローしているかの確認
  def  following?(other_user)
      self.follow_friends.find_by(to_user_id: other_user)
  end
  #友達登録
  def follow(other_user)
    self.follow_friends.find_or_create_by(to_user_id: other_user.id)
  end
  
  def friend?(other_user)
    self.follow_friends.find_by(to_user_id: other_user,request: true)
  end
  #フレンドを削除
  def unfollow(other_user)
    self.follow_friends.find_by(to_user_id: other_user.id)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = "password"
      user.confirmed_at = Time.now  
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :get_profile,only:[:show,:destroy,:edit,:update] 
  before_action :authenticate_user!,only:[:index,:new, :create, :edit, :update, :destroy]
  before_action :current_profile,only:[:group,:article,:mypage]
  
  def index
    @profiles=Profile.where('nickname LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.profile.id)
      respond_to do |format|
        format.html
        format.json
      end
    
  end

  def new
    if current_user.profile.nil?
      @profile=Profile.new
    else
      redirect_to root_path
    end
  end

  def create
    if @profile=Profile.new(profile_params)
    #update以外のやり方もないのか検証をする
      @profile.update(user_id: current_user.id)
      @profile.save
    else
      render "new"
    end
  end

  def show
    @articles=Article.includes([:article_images,:profile]).where(profile_id: @profile).as_json(include: {article_images: {only: [:id,:picture]}})
    @groups=Group.includes(:members).where(members: {profile_id: current_user.profile.id})
    @friend=current_user.profile.follower_friends.build
  end

  def edit
    unless current_user.id == @profile.user_id
      redirect_to root_path
    end
  end

  def update
    @profile.update(profile_params)
    redirect_to root_path
  end

  def destroy
    
  end

  def friend
    @follow_friends =Friend.where(from_user_id: current_user.profile.id,request: true)
    @profile=current_user.profile.follow_friends
    @friends=Friend.where(to_user_id: current_user.profile.id,request: false)
  end

  def mypage
    @first_article=@profile.articles.first
    @comments=@profile.comments
    @articles=Article.includes([:article_images,:profile]).where(profile_id: @profile).as_json(include: {article_images: {only: [:id,:picture]}})
    @groups=Group.includes(:members).where(members: {profile_id: current_user.profile.id})
  end

  def group
    @groups=@profile.groups
    @group=Group.page(params[:page]).per(5)
  end

  def article
    @article=@profile.articles
    @article=Article.page(params[:page]).per(6)
  end

  def search
    @profile = Profile.where('nickname LIKE?', "%#{params[:nickname]}%").where.not(id: current_user.profile.id).page(params[:page]).per(5)
    @friend=current_user.profile.follower_friends.build
  end

  def friend_request
    @friends=Friend.where(to_user_id: current_user.profile.id,request: false)
  end

  private
    def profile_params
      params.require(:profile).permit(:nickname,:avatar,:text)
    end

    def get_profile
      @profile=Profile.find(params[:id])
    end

    def current_profile
      @profile=current_user.profile
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_profile-form.html.haml
- if controller.action_name == "edit"
  #profile-edit-preview
    -if @profile.avatar.url.present?
      =image_tag(@profile.avatar.url,height:"150px",width:"150px",class: "profile-edit-img")
    -else
      =image_tag("icon_image.jpeg",width:"150px",height:"150px",class: "profile-edit-img")
- if controller.action_name == "edit"     
  .profile-edit-avatar
    -if @profile.avatar.url.present?
      =f.file_field :avatar,value:@profile.avatar
    -else
      =f.file_field :avatar
  .profile-edit-nickname
    =f.label "ニックネーム"
    =f.text_field :nickname,placeholder:@profile.nickname
  .profile-edit-text
    =f.label "紹介文"
    =f.text_area :text,size:"40x4",placeholder:@profile.text
  .profile-edit-button
    =f.submit "編集する"
-else
  .profile-new-nickname
    =f.label :nickname
    = f.text_field :nickname
  .profile-new-avatar
    =f.label :avatar
    = f.file_field :avatar,id:"avatar-img"
    -if @profile.avatar.present?
      =image_tag(@profile.avatar.url,id: "avatar-preview",height:"150px",width:"200px")
    -else
      =image_tag("sample1.jpeg",id: "avatar-preview")
  .profile-new-text
    =f.label :text
    = f.text_area :text
  .profile-new-button
    = f.submit "新規登録",class:"profile-new-submit"

app/views/profiles/_profile-page.html.haml
.profile-wrapper
  .profile-contents
    .profile-upper
      .profile-upper__box
        .profile-avatar
          - if @profile.avatar.url.nil?
            =image_tag("sample1.jpeg",width:"200px",height:"200px",class:"avatar-image")
          - else
            =image_tag(@profile.avatar.url,width:"200px",height:"200px",class:"avatar-image")
      .profile-upper__box
        .profile-user
          .profile-name
            = @profile.nickname
        .profile-user
          -if @profile.id == current_user.profile.id
            .profile-button
              =link_to "EDIT",edit_profile_path(@profile),class:"profile-link"
          - else
            .profile-button
              -unless @profile.id == current_user.profile.id
                -if current_user.profile.following?(@profile)
                  =form_with(model:@friend,url: friends_path) do |f|
                    = f.hidden_field :to_user_id,value:"#{@profile.id}" 
                    =f.submit "友達解除",class:"user-search-link"
                -else
                  =form_with(model:@friend,url: friends_path) do |f|
                    = f.hidden_field :to_user_id,value:"#{@profile.id}" 
                    =f.submit "友達申請を送る",class:"user-search-link"
        .profile-show-center
          =link_to friend_profile_path(@profile) do
            =icon('fas', 'user-friends')
            友達リスト
        .profile-show-center
          =link_to group_profile_path(@profile) do
            =icon('fas', 'users')
            グループリスト
        .profile-introduction
          =@profile.text
    .profile-center
      .profile-map
        .album-title
          ="#{@profile.nickname}のcluster's album"
        .google_maps
          = react_component("maptest",{first_article:@first_article,articles: @articles,article_group: @groups})

app/views/profiles/_profile.html.haml
.profile-friend-boxs
  .profile-friend-box
    .profile-friend-avatar
      -if profile.avatar.url.nil?
        =image_tag("sample1.jpeg",height:"150px",width:"150px",class:"profile-friend-image")
      -else
        =image_tag(profile.avatar.url,height:"150px",width:"150px",class:"profile-friend-image")
  .profile-friend-box
    .profile-friend-right
      .profile-friend-nickname
        =link_to profile.nickname,profile_path(profile),class:"profile-friend-link"
    .profile-friend-right
      .profile-friend-button
        -if current_user.profile.following?(profile)
          =form_with(model:@friend,url: friends_path) do |f|
            = f.hidden_field :to_user_id,value:"#{profile.id}" 
            =f.submit "フォロー解除",class:"user-search-link"
        -else
          =form_with(model:@friend,url: friends_path) do |f|
            = f.hidden_field :to_user_id,value:"#{profile.id}" 
            =f.submit "フォロー",class:"user-search-link"
    .profile-friend-introduction
      =profile.text

app/views/profiles/article.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
.profile-article-wrapper
  .profile-article-contents
    %ul.profile-article-boxs
      - @article.each do |article|
        %li.profile-article-box
          .profile-article-title
            =link_to "#{article.title}",article_path(article),class:"profile-article-link"
          .profile-article-picture
            -if article.article_images.blank?
              =image_tag("sample1.jpeg",width:"200px",height:"200px",class: "profile-article-image")
            - else
              =image_tag(article.article_images.first.picture.url,width:"200px",height:"200px",class: "profile-article-image")
          .profile-article-under
            %p.profile-article-introduction
              -if article.introduction.blank?
                = "現在、紹介文はありません"
              - else
                = article.introduction
    .profile-article-page
      = paginate @article

app/views/profiles/create.thml.haml
.profile-create-wrapper
  .profile-create-contents
    

app/views/profiles/edit.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
.profile-edit-wrapper
  .profile-edit-contents
    .profile-edit-box
      .profile-edit-title
        プロフィール編集画面
      .profile-edit-form
        =form_with(model:@profile,local: true) do |f|
          =render "profile-form",{f: f}
      .profile-edit-user
        =link_to "ユーザー編集",edit_user_registration_path(@profile)

app/views/profiles/friend.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
.profile-friend-wrapper
  .profile-friend-contents
    .profile-friend-title
      フォロー一覧
    %ul.profile-friend-list
      - @follow_friends.each do |follow_friend|
        .profile-friend-boxs
          .profile-friend-box
            .profile-friend-avatar
              =image_tag("#{follow_friend.to_user.avatar.url}",height:"150px",width:"150px",class:"profile-friend-image")
          .profile-friend-box
            .profile-friend-right
              .profile-friend-nickname
                =link_to("#{follow_friend.to_user.nickname}",profile_path(follow_friend.to_user),class:"profile-friend-link")
            .profile-friend-right
              .profile-friend-button
                = form_with(model: follow_friend,method: :delete) do |f|
                  =f.submit "友達を解除"
            .profile-friend-introduction
              -if follow_friend.to_user.text.blank?
                紹介文なし
              -else
                =follow_friend.to_user.text

app/views/profiles/friend_request.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
.friend-request-wrapper
  .friend-request-contents
    .friend-request-box
      %h2.friend-request-title
        =icon('fas','address-card fa-lg')
        あなたは今こちらの方から友達申請を受けています
      -@friends.each do |friend|
        .friend-request-boxs
          .friend-request-section
            =image_tag(friend.from_user.avatar.url,width:"150px",height:"150px",class:"friend-request-img")
          .friend-request-section
            =friend.from_user.nickname
            = react_component("Modalwindow", {friend: friend, from_user: friend.from_user})
   

app/views/profiles/group.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
.profile-group-wrapper
  .profile-group-contents
    .profile-group-title
      %h2 所属グループ一覧
    .profile-group-list
      - @groups.each do |group|
        .profile-group-boxs
          .profile-group-box
            .profile-group__icon
              -if group.articles.blank?
                =image_tag("sample1.jpeg",height:"150px",width:"150px")
              -else
                =image_tag(group.articles[0].article_images[0].picture.url,height:"150px",width:"150px")
          .profile-group-box
            .profile-group_name
              =link_to  "#{group.name}",group_path(group)
            .profile-group-text
              =group.text
          .profile-group-box
            登録記事
            .profile-group-articles
              -unless group.articles.blank?
                -group.articles.first(5).each do |article|
                  .profile-group-article
                    =article.title

app/views/profiles/index.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
.profile-wrapper
  .profile-contents
    .profile-search
      =form_with(url: search_profiles_path,method: :get,local: true) do |f|
        = f.text_field :nickname,id:"search-input",placeholder:"ここにユーザー名を入力してください"
        =f.submit "検索する",id:"search-button" 
    

app/views/profiles/mypage.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
=render partial: "profile-page"

app/views/profiles/new.html.haml
.profile-new-wrapper
  .profile-new-contents
    .profile-new-box
      .profile-new-title
        プロフィール登録
      .profile-new-form
        =form_with(model:@profile,local: true) do |f|
          =render "profile-form",{f: f}

app/views/profiles/search.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
.profile-wrapper
  .profile-contents
    .profile-search
      =form_with(url: search_profiles_path,method: :get,local: true) do |f|
        = f.text_field :nickname,id:"search-input"
        =f.submit "検索する",id:"search-button"
    -if @profile.blank?
      = "該当するユーザーはいませんでした"    
    %ul.group-list-box
      = render @profile
    .group-page
      = paginate @profile

app/views/profiles/show.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
=render partial: "profile-page"