config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    get 'omniauth' => 'users/registrations#omniauth'
    post 'users/guest_user', to: 'users/sessions#guest_user'
  end
  resources :articles do
    get :search,on: :collection
  end

  resources :main_pages
  resources :top_pages

  resources :profiles do
    get :search, on: :collection
   member do
    get "friend"
    get "article"
    get "group"
    get "comment"
    get "friend_request"
   end
  end

  resources :friends,only:[:create,:destroy,:update]
   
  resources :comments
  resources :groups do
    get :search, on: :collection
    member do
       post "register"
    end
  end

  get 'profile', to: 'profiles#mypage'

  authenticated :user do
    root :to => 'profiles#mypage'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "top_pages#index"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :introduction, presence: true
  validates :text,presence: true
  validate :check_image

  has_many :article_images, dependent: :destroy
  accepts_nested_attributes_for :article_images, allow_destroy: true
  has_many :categories
  belongs_to :group
  
  has_many :comments, dependent: :destroy
  belongs_to :profile

  def check_image
    if article_images.empty?
      errors.add(:article_images, "がありません")
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!,only:[:index,:new, :create, :edit, :update, :destroy]
  before_action :get_article,only:[:show,:edit,:update]
  
  def index
    @articles=Article.all.page(params[:page]).per(9)
    
  end

  def new
    unless user_signed_in?
      redirect_to root_path
    end
    @article=Article.new
    @article.article_images.build
    @groups=Group.includes(:members).where(members: {profile_id: current_user.profile.id})
    @lat=params[:lat]
    @lng=params[:lng]
  end

  def create
    @article=Article.new(article_params)
    #update以外の関連付けは？
    @article.update(profile_id: current_user.profile.id)
    if @article.save
      redirect_to articles_url
    else
      render "new"
    end
  end

  def show
    @articles=@article.as_json(include: {article_images: {only: [:id,:picture]}})
    @comment=Comment.new
    @comment.comment_images.build
  end

  def edit
    unless current_user.profile.id == @article.profile_id
      redirect_to root_path
    end
    @groups=Group.includes(:members).where(members: {profile_id: current_user.profile.id})
  end

  def update
    if @article.update(article_params)
         redirect_to root_path
    else render "edit"
    end
  end

  def destroy
    @article=Article.find(params[:id]).destroy
  end

  def search
    @article = Article.where('title LIKE?', "%#{params[:title]}%").page(params[:page]).per(5)
  end

  private
    def article_params
      params.require(:article).permit(:title,:introduction,:text,:lat,:lng,:group_id,article_images_attributes: [:id,:_destroy,:picture,:introduction])
    end

    def get_article
     @article=Article.find(params[:id])
    end
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article-form.html.haml
.article-edit-title
  =f.label "題名",class:"form-label"
  %span.form-tag 必須
  - if controller.action_name == "new"
    = f.text_field :title,placeholder:"ここに記事の名前を入力してください"
  -else
    = f.text_field :title,placeholder:@article.title
.article-new-group  
  -if @groups.blank?
    - @article.group_id=1
    =@article.group.name
  -else
    = f.collection_select(:group_id,@groups,:id,:name)
.article-edit-introduction
  =f.label "紹介文",class:"form-label"
  - if controller.action_name == "new"
    =f.text_field :introduction,placeholder:"ここに紹介文を入力してください"
  -else
    = f.text_field :introduction,placeholder:@article.introduction
.article-edit-text
  =f.label "本文"
  %span.form-tag 必須
  - if controller.action_name == "new"
    =f.text_area :text,size:"80x20",placeholder:"ここに本文を入力してください"
  - else
    = f.text_area :text,size:"80x20",placeholder:@article.text

app/views/articles/_article.html.haml
.article-detail-box
  .article-detail-boxs
    -if article.article_images.blank?
      =image_tag("sample1.jpeg",class: "article-picture",width:"100px",height:"100px")
    -else
      =image_tag(article.article_images.first.picture.url,class: "article-picture",width:"100px",height:"100px")
  .article-detail-boxs
    記事名
    %br
    .article-detail-title
      = link_to article.title,article_path(article)
  .article-detail-boxs
    説明文
    %br
    -if article.introduction.nil?
      紹介文なし
    -else  
      =article.introduction  

app/views/articles/edit.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
.article-edit-wrapper
  .article-edit-contents
    .article-edit-form
      %h2 編集画面
      =form_with model: @article,local: true do |f|
        =render "article-form",{f: f}
        .article-edit-block
          .article-new-preview
            -@article.article_images.each_with_index do |image,num|
              .img-view
                .img-section
                  =image_tag(image.picture.url,width:"150px",height:"150px",class:"preview",data:{index: num})
                .img-section
                  .btn-wrapper 
                    .btn-section
                      .btn-edit
                        編集
                    .btn-section
                      .btn-delete
                        削除
        .article-edit-block
          = f.fields_for :article_images do |ff|
            //= ff.label  :picture, class: "label-box", for: "upload-image-#{@article.article_images.length}" do
            //%p.label-box__text-visible クリックしてファイルをアップロード
            .article-edit--box
              .article-new-file-field
                .article-new-input{"data-index" => "#{ff.index}"}
                  = ff.file_field :picture, name: "article[article_images_attributes][#{ff.index}][picture]", id: "upload-image-#{ff.index}",class:"upload-image",style:"display:none"
                  = ff.text_area :introduction,size:"40x4",name: "article[article_images_attributes][#{ff.index}][introduction]", id: "upload-image-#{ff.index}",placeholder:@article.article_images[ff.index].introduction
                  = ff.check_box :_destroy,style:"display:none"
          =f.fields_for @article.article_images.build do |ff|
            .article-edit-file-field
              .article-edit-input{"data-index"=>"#{@article.article_images.length - 1}"}
                =ff.file_field :picture,name: "article[article_images_attributes][#{@article.article_images.length - 1}][picture]", id: "upload-image-#{@article.article_images.length - 1}",class:"upload-image"
        = f.collection_select(:group_id,Group.all,:id,:name)
        //test用
        =f.hidden_field :profile_id,value:"#{current_user.profile.id}"
        =f.submit "編集する"

app/views/articles/index.html.haml
=render partial:"shared/header"
=render partial: "shared/side_bar"
.article_wrapper
  .article-contents
    .article-box
      記事検索画面
      =form_with(url: search_articles_path,method: :get,local: true) do |f|
        = f.text_field :name,id:"search-input",placeholder:"ここに記事名を入力してください"
        =f.submit "検索する",id:"search-button"

app/views/articles/new.html.haml
=render partial:"shared/header"
=render partial: "shared/side_bar"
.article-new-wrapper
  .article-new-contents
    .article-new-box
      .article-new-title
        新規記事作成
      .article-new-form
        = form_with(model:@article,local:true,:builder=>CustomFormBuilder) do |f|
          =render "article-form",{f: f}
          =f.hidden_field :lat,value:@lat
          =f.hidden_field :lng,value:@lng
          //#article_image_box
          .article-new-preview
          = f.fields_for :article_images do |ff|
            .article-new-file-field
              .article-new-input{"data-index" => "#{ff.index}"}
                =ff.file_field :picture,class:"article_article_images_attributes_0_picture",id:"article_article_images_attributes_0_picture"
            //= f.fields_for :article_images do |ff|
            //=ff.file_field :picture,accept: 'image/jpeg,image/jpg,image/png'
          .article-new-button
            = f.submit "送信",class:"article-new-submit"


//=f.label(:article_images_attributes_0_picture,class: "label-box",id: "article_image_box") do
//%p.article-new-image-title
//ここをクリックするとアップロードできます

app/views/articles/search.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
=form_with(url: search_articles_path,method: :get,local: true) do |f|
  = f.text_field :name,id:"search-input",placeholder:"ここに記事名を入力してください"
  =f.submit "検索する",id:"search-button"
-if @article.blank?
  = "該当する記事がありませんでした"
%ul.group-list-box
  = render @article
.group-page
  = paginate @article
        

app/views/articles/show.html.haml
=render partial:"shared/header"
=render partial: "shared/side_bar"
.article-show-wrapper
  .article-show-contents
    .article-show-upper-box
      .article-show-title
        %h3= @article.title
      .article-show-title
        =link_to "edit",edit_article_path(@article)
        =link_to "delete",article_path(@article),method: :delete
      .article-show-nickname
        記事の投稿者
        =@article.profile.nickname
      .article-show-group
        所属グループ名
        -if @article.group.nil?
          = "グループ未指定"
        - else
          =@article.group.name 
    .article-show-center-box
      -if @article.text.blank?
        記事に紹介文が書かれていません
      -else
        = @article.text
    = react_component("preview",{articles: @article.article_images})
    .article-show-comments
      コメント欄
      - @article.comments.each do |article|
        .article-show-comment
          .article-show-comment__left
            =image_tag(article.profile.avatar.url,width:"100px",height:"100px",class: "article-show-avatar")
            .article-show-comment--user
              =link_to article.profile.nickname,profile_path(article.profile.id)
          .article-show-comment--text
            =article.text
            -unless article.comment_images.blank?
              -article.comment_images.each do |image|
                =image_tag(image.picture.url,width:"10zpx",height:"100px")
    .article-show-form
      =form_with(model:@comment,url: comments_path) do |f|
        .article-show-form__box
          = f.text_field :text
          = f.fields_for :comment_images do |ff|
            %label
              =icon('fas', 'folder-open') 
              =ff.file_field :picture,class:"article-show-form--uploader"
        .article-show-form__box
          = f.hidden_field :article_id,value:@article.id
          =f.submit "コメントを送信する"
        
                  