config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    get 'omniauth' => 'users/registrations#omniauth'
    post 'users/guest_user', to: 'users/sessions#guest_user'
  end
  resources :articles do
    get :search,on: :collection
  end

  resources :main_pages
  resources :top_pages

  resources :profiles do
    get :search, on: :collection
   member do
    get "friend"
    get "article"
    get "group"
    get "comment"
    get "friend_request"
   end
  end

  resources :friends,only:[:create,:destroy,:update]
   
  resources :comments
  resources :groups do
    get :search, on: :collection
    member do
       post "register"
    end
  end

  get 'profile', to: 'profiles#mypage'

  authenticated :user do
    root :to => 'profiles#mypage'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "top_pages#index"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :profiles, through: :members
  has_many :articles
  validates :name,presence: true, length: { maximum: 20 }
  validates :text,presence: true, length: { maximum: 80 }
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!,only:[:index,:new, :create, :edit, :update, :destroy]
  before_action :get_group,only:[:show,:edit,:update,:destroy]
  def index
    @groups=Group.all.page(params[:page]).per(5)
  end

  def new
    @group=Group.new
    #@members=Friend.where(from_user_id: current_user.profile.id,request: true)
    #@member=User.includes([:profile]).where(id: @members[0].to_user_id)
  end

  def create
    @group=Group.new(group_params)
    @group.update(admin_user_id: current_user.profile.id )
    if @group.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def show
    @member=@group.members.find_by(profile_id: current_user.profile)
    @articles=Article.includes([:article_images,:profile]).where(group_id: @group).as_json(include: {article_images: {only: [:id,:picture]}})

  end

  def edit
    unless current_user.profile.id == @group.admin_user_id
       redirect_to root_path
    end
  end

  def update
    @group.update(group_params)
  end

  def destroy
    
  end

  def search
    @group = Group.where('name LIKE?', "%#{params[:name]}%").page(params[:page]).per(5)
    
    
  end

  def register
    @group=Group.find(params[:id])
    if current_user.profile.friend?(@group.admin_user_id)  
      @member=@group.members.build
      @member.update(profile_id: current_user.profile.id)
    else 
      redirect_to root_path
    end
  end

  private

    def group_params
      params.require(:group).permit(:name,:text,{:profile_ids => []})
    end

    def get_group
      @group=Group.find(params[:id])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group.html.haml
.profile-group-boxs
  .profile-group-box
    .profile-group__icon
      -if group.articles.blank?
        =image_tag("sample1.jpeg",height:"150px",width:"150px")
      -else
        =image_tag(group.articles[0].article_images[0].picture.url,height:"150px",width:"150px")
  .profile-group-box
    .profile-group_name
      =link_to  "#{group.name}",group_path(group)
    .profile-group-text
      =group.text
  .profile-group-box
    登録記事
    .profile-group-articles
      -unless group.articles.blank?
        -group.articles.first(5).each do |article|
          .profile-group-article
            =article.title

app/views/groups/_group_form.html.haml
=form_with(model: @group,local: true,:builder=>CustomFormBuilder) do |f|
  .group-new-boxs
    %span.form--label
      必須
    =f.label "グループ名",class:"group-new-label"
    = f.text_field :name,class:"group-new-input",placeholder:"ここにグループ名を入力してください"
  .group-new-boxs
    =f.label "紹介文",class:"group-new-label"
    = f.text_area :text,size:"40x5",class:"group-new-textarea",placeholder:"グループを紹介する文章を記入しよう"
  - if controller.action_name == "new"
    %input{name: 'group[profile_ids][]', type: 'hidden', value: "#{ current_user.profile.id }"}
  .group-new-boxs
    メンバー 一覧
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "user-search-field"}メンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input.chat-group-form__input{id: 'user-search-field',placeholder: '追加したいユーザー名を入力してください',type:'text',name:"keyword"}
        #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :profile_ids, "メンバー", class: 'chat-group-form__label'
    .chat-group-form__field--right
      #chat-group-users
        - @group.profiles.each do |user|
          .chat-group-user
            %input{name: 'group[profile_ids][]', type: 'hidden', value: "#{ user.id }"}
            %p.chat-group-user__names
              = user.nickname
            %p.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除

      #member_search_result


  =f.submit "送信",class:"group-new-button"

app/views/groups/create.html.haml
.group-create-wrapper
  .group-create-contents
    .group-create-box
      グループの作成が完了しました

app/views/groups/edit.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
.group-edit-wrapper
  .group-edit-contents
    %h2 グループ編集画面
    =render partial: "group_form"

app/views/groups/index.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
.group-wrapper
  .group-contents
    .group-context
      .group-search-title
        グループ検索欄
        .group-form
          =form_with(url: search_groups_path,method: :get,local: true) do |f|
            = f.text_field :name,id:"search-input",placeholder:"ここにグループ名を入力してください"
            =f.submit "検索する",id:"search-button"

app/views/groups/new.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
.group-new-wrapper
  .group-new-contents
    .group-new-box
      .group-new-header
        グループ作成画面
      =render partial: "group_form"

app/views/groups/search.html.haml
=render partial: "shared/header"
=render partial: "shared/side_bar"
.group-wrapper
  .group-contents
    .group-context
      .group-search-title
        グループ検索欄
        .group-form
          =form_with(url: search_groups_path,method: :get,local: true) do |f|
            = f.text_field :name,id:"search-input"
            =f.submit "検索する",id:"search-button"
        -if @group.blank?
          ="該当するグループはありませんでした"
        %ul.group-list-box
          = render @group
        .group-page
          = paginate @group
            

app/views/groups/show.html.haml
=render partial:"shared/header"

.group-show-wrapper
  .group-show-contents
    .group-show-upper
      グループ名
      .group-show-title
        =@group.name
        =link_to "edit",edit_group_path(@group)
      .group-show-introduction
        =@group.text
      .group-show-register
        -if @member.present?
          参加済み
        -else
          =form_with(url: register_group_path) do |f|
            =f.submit "参加する"
    .group-show-center
      .group-show-map
        = react_component("maptest2",{articles: @articles})
    .group-show-right
      %ul.group-show-right__box
        メンバー一覧
        -@group.members.each do |member|
          %li.group-show-member
            =link_to "#{member.profile.nickname}",profile_path(member.profile_id)