config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    get 'omniauth' => 'users/registrations#omniauth'
    post 'users/guest_user', to: 'users/sessions#guest_user'
  end
  resources :articles do
    get :search,on: :collection
  end

  resources :main_pages
  resources :top_pages

  resources :profiles do
    get :search, on: :collection
   member do
    get "friend"
    get "article"
    get "group"
    get "comment"
    get "friend_request"
   end
  end

  resources :friends,only:[:create,:destroy,:update]
   
  resources :comments
  resources :groups do
    get :search, on: :collection
    member do
       post "register"
    end
  end

  get 'profile', to: 'profiles#mypage'

  authenticated :user do
    root :to => 'profiles#mypage'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "top_pages#index"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :introduction, presence: true
  validates :text,presence: true
  validate :check_image

  has_many :article_images, dependent: :destroy
  accepts_nested_attributes_for :article_images, allow_destroy: true
  has_many :categories
  belongs_to :group
  
  has_many :comments, dependent: :destroy
  belongs_to :profile

  def check_image
    if article_images.empty?
      errors.add(:article_images, "がありません")
    end
  end
  
end

app/models/article_image.rb
class ArticleImage < ApplicationRecord
  belongs_to :article
  mount_uploader :picture, PictureUploader
  validate  :picture_size
  validates :picture,presence: true

  private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :group
  belongs_to :article
  
end

app/models/category_name.rb
class CategoryName < ApplicationRecord
  has_many :categories
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :comment_images, dependent: :destroy
  accepts_nested_attributes_for :comment_images
  belongs_to :profile
  belongs_to :article
  validates :text,presence: true
end

app/models/comment_image.rb
class CommentImage < ApplicationRecord
  belongs_to :comment, optional: true
  mount_uploader :picture, PictureUploader
  
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :from_user, class_name: "Profile"
  belongs_to :to_user, class_name: "Profile"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :profiles, through: :members
  has_many :articles
  validates :name,presence: true, length: { maximum: 20 }
  validates :text,presence: true, length: { maximum: 80 }
  
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :profile
  belongs_to :group
  
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :articles
  has_many :members
  has_many :groups, through: :members
  mount_uploader :avatar, AvatarUploader
  has_many :follow_friends,  class_name:  "Friend",
                                   foreign_key: "from_user_id",
                                   dependent:   :destroy
  has_many :follower_friends, class_name:  "Friend",
                                   foreign_key: "to_user_id",
                                   dependent:   :destroy
  has_many :from_users, through: :follower_friends,  source: :from_user
  has_many :to_users, through: :follow_friends, source: :to_user
  validates :nickname,presence: true
  validates :text,presence: true

  #フォローしているかの確認
  def  following?(other_user)
      self.follow_friends.find_by(to_user_id: other_user)
  end
  #友達登録
  def follow(other_user)
    self.follow_friends.find_or_create_by(to_user_id: other_user.id)
  end
  
  def friend?(other_user)
    self.follow_friends.find_by(to_user_id: other_user,request: true)
  end
  #フレンドを削除
  def unfollow(other_user)
    self.follow_friends.find_by(to_user_id: other_user.id)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = "password"
      user.confirmed_at = Time.now  
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :members
  has_many :groups, through: :members
  has_one :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :rememberable,:confirmable,
         :omniauthable, omniauth_providers: %i[facebook twitter google_oauth2]
  # @return [Boolean] user should be remembered when he logs in (with cookie)
  #   so he won't be asked to login again
  #validates :cell_phone,presence: true
  def remember_me
    true
  end

  # sns認証後、ユーザーの有無に応じて挙動を変更する
  def self.from_omniauth(auth)
    # uidとproviderでユーザーを検索
    user = User.find_by(uid: auth.uid, provider: auth.provider)
    if user
      #Trueの場合は既にあるUserを返す
      return user
    else
      #falseの場合は新規作成
      new_user = User.new(
        email: auth.info.email,
        uid: auth.uid,
        provider: auth.provider,
        #パスワードにnull制約があるためFakerで適当に作ったものを突っ込んでいます
        password: Faker::Internet.password(min_length: 7,max_length: 128)
      )
      return new_user
    end
  end
  #ゲストユーザー用の関数
  def self.guest    
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = "password"
      user.confirmed_at = Time.now  
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClusterAppSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_group.html.haml
.profile-group-boxs
  .profile-group-box
    .profile-group__icon
      -if group.articles.blank?
        =image_tag("sample1.jpeg",height:"150px",width:"150px")
      -else
        =image_tag(group.articles[0].article_images[0].picture.url,height:"150px",width:"150px")
  .profile-group-box
    .profile-group_name
      =link_to  "#{group.name}",group_path(group)
    .profile-group-text
      =group.text
  .profile-group-box
    登録記事
    .profile-group-articles
      -unless group.articles.blank?
        -group.articles.first(5).each do |article|
          .profile-group-article
            =article.title

app/views/shared/_header.html.haml
%header.header
  .header-container
    .header-left
      .header-left-box
        =link_to "cluster's album",root_path,class:"header-link"
    .header-right
      .header-right__box
        =link_to "group-search",groups_path,class:"header-link"  
      .header-right__box
        =link_to "article-search",articles_path,class:"header-link"  
      .header-right__box
        =link_to "user-search",profiles_path,class:"header-link"
      .header-right__box
        - if user_signed_in?
          =link_to "logout",destroy_user_session_path,class:"header-link", method: :delete
        -else 
          =link_to "login",new_user_session_path,class:"header-link"

app/views/shared/_side_bar.html.haml
.side-bar-wrapper
  .side-bar-upper
    .side-bar-upper__box
      .side-bar-upper__section
        .side-bar-upper--avatar
          -if current_user.profile.avatar.url.nil?
            =image_tag("icon_image.jpeg",width:"100px",height:"100px",class: "side-bar-upper--image")
          - else
            =image_tag(current_user.profile.avatar.url,height:"100px",width:"100px",class: "side-bar-upper--image")
      .side-bar-upper__section
        .side-bar-user 
          =link_to current_user.profile.nickname,root_path,class:"side-bar--link"
          .side-bar-friend 
            //関連付けを行ったパスを
            =link_to friend_profile_path(current_user.profile),class:"side-bar--link" do
              =icon('fas', 'user-friends')
              友達リスト
          .side-bar-group  
            =link_to group_profile_path(current_user),class:"side-bar--link" do
              =icon('fas', 'users')
              groupリスト
      .side-bar-request
        .side-bar-request__box
          =link_to friend_request_profile_path(current_user.profile),class:"side-bar--link" do
            =icon('fas', 'user-plus')
            友達リクエスト一覧
      .side-bar-new-group
        //関連付けを行ったパスを
        =link_to new_group_path,class:"side-bar--link" do
          =icon('fas', 'layer-group')
          グループ作成"
      .side-bar-article
        //関連付けを行ったパスを
        =link_to article_profile_path(current_user) ,class:"side-bar--link" do
          =icon('fas', 'folder-open')
          記事一覧

app/views/shared/_side_box.html.haml
.side-bar-under__box
  .side-bar-under--group
    お気に入り記事一覧